#!/bin/bash

## Bash-In-the-Box (BItBox)
## Copyright © 2026 Francesco Napoleoni
##
## This file is part of “Bash-In-the-Box”.
##
## “Bash-In-the-Box” is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by the
## Free Software Foundation, either version 3 of the License, or (at your
## option) any later version.
##
## “Bash-In-the-Box” is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
## more details.
##
## You should have received a copy of the GNU General Public License along with
## “Bash-In-the-Box”. If not, see <https://www.gnu.org/licenses/>.


########################################


declare -A conf=(
    ["interactive"]=1
#     ["name"]="bitbox_test"
    ["longname"]="Bash-In-the-Box test runner"
    ["unittest.verbose"]=0
    ["style"]=1
    ["version"]="0.1"
)

source ${BIB_HOME}/bitbox/main.lib.sh conf
bib.include unittest.unittest

declare -A TESTS
declare TEST_PATH="${PWD}/tests"


########################################


###############
## FUNCTIONS ##
###############

#/**
# * Helper function that runs a single test and prints the results.
# *
# * Syntax: _run_test TEST_NAME
# *
# * @param TEST_NAME
# *
# * Exit codes:
# * * BIB_E_OK
# * * BIB_E_NEXISTS if the file containing the test was not found
# * * BIB_E_TESTFAIL
# */
function _run_test() {
    local _test_name
    local _test_path
    local _test_code
    local -i __status=${BIB_E_OK}

    _test_name="${1}"

    _test_path+="${TEST_PATH}/${_test_name}.test.sh"

    [[ -f "${_test_path}" ]] || return ${BIB_E_NEXISTS}

    _test_code="declare -i status=\${BIB_E_OK}

$(<"${_test_path}")


########################################


setup
bib.unittest.run \"\${@}\" || status=\${BIB_E_TESTFAIL}
teardown
bib.print -n '\n'
bib.unittest.stats

exit \${status}
"
    (/bin/bash -c "${_test_code}") || __status=${BIB_E_TESTFAIL}

    return ${__status}
}


#/**
# * Runs the test suite.
# *
# * Syntax: run_test TEST_NAME
# *
# * @param TEST_NAME
# *
# * Exit codes:
# * * BIB_E_OK
# * * BIB_E_TESTFAIL
# */
function run_tests() {
    local -n _tests="${1}"
    local _test
    local -i _status=${BIB_E_OK}
    local -i _i=0

    (( ${#_tests[@]} > 0 )) || return ${BIB_E_NOK}

    for _test in ${!_tests[@]}
    do
        if (( ! _tests["${_test}"] ))
        then
            bib.print "*Test “${_test}” skipped*\n"
            (( _i++ ))
            continue
        fi

        (( _i > 0 )) && bib.print -n "\n----------\n\n"
        bib.print -n "Testing “${_test}”\n"

        _run_test "${_test}"
        case ${?} in
            ${BIB_E_NEXISTS} )
                bib.print "&RED*Test “${_test}” not found in path*\n"
                _status=${BIB_E_NOK}
            ;;

            ${BIB_E_TESTFAIL} )
                bib.print "&YLW*Test “${_test}” failed*\n"
                _status=${BIB_E_NOK}
            ;;

            ${BIB_E_OK} )
                bib.print "&GRN*Test “${_test}” OK*\n"
            ;;
        esac

        (( _i++ ))
    done

    return ${_status}
}


########################################


##########
## MAIN ##
##########


while getopts ":d:v" OPTION
do
    case "${OPTION}" in
        "d" )
            TEST_PATH="${OPTARG}"
        ;;

        "v" )
            BIB_UNITTEST_VERBOSE=${BIB_TRUE}
        ;;
    esac
done

shift $(( OPTIND - 1 ))

if [[ ! -d "${TEST_PATH}" ]]
then
    bib.error "${TEST_PATH} not found or inaccessible."
    exit ${BIB_E_NEXISTS}
fi

if (( ${#} > 0 ))
then
    TESTS=()
    for _test_name in "${@}"
    do
        TESTS["${_test_name}"]=1
    done
else
    source "${TEST_PATH}/tests.conf"
fi

run_tests TESTS
