#!/bin/bash

## Bash-In-the-Box (BItBox)
## Copyright © 2024 Francesco Napoleoni
##
## This file is part of “Bash-In-the-Box”.
##
## “Bash-In-the-Box” is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by the
## Free Software Foundation, either version 3 of the License, or (at your
## option) any later version.
##
## “Bash-In-the-Box” is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
## more details.
##
## You should have received a copy of the GNU General Public License along with
## “Bash-In-the-Box”. If not, see <https://www.gnu.org/licenses/>.


########################################


declare -a tests=(
    "main"
    "style"
    "filedir"
    "array"
    "cfg"
    "log"
)

declare -A tests_enabled=(
    ["main"]=1
    ["style"]=1
    ["filedir"]=1
    ["array"]=1
    ["cfg"]=1
    ["log"]=1
)

declare -A tests_results

declare -A conf=(
    ["interactive"]=1
    ["name"]="bitbox_test"
    ["longname"]="Bash-In-the-Box test suite"
    ["unittest.verbose"]=0
    ["style"]=1
    ["version"]="0.1"
)

source ${BIB_HOME}/bitbox/main.lib.sh conf
bib.include unittest.unittest

declare test_path="tests"
declare -i status=${BIB_E_OK}


########################################


###############
## FUNCTIONS ##
###############

function run_test() {
    local _test_name
    local _test_path
    local _test_code
    local -i __status=${BIB_E_OK}

    _test_name="${1}"

    _test_path+="${test_path}/${_test_name}.test.sh"

    [[ -f "${_test_path}" ]] || return ${BIB_E_NEXISTS}

    _test_code="declare -i status=\${BIB_E_OK}

$(<"${_test_path}")


########################################


setup
bib.unittest.run \"\${@}\" || status=\${BIB_E_TESTFAIL}
teardown
bib.print -n '\n'
bib.unittest.stats

exit \${status}
"
    (/bin/bash -c "${_test_code}") || __status=${BIB_E_TESTFAIL}

    return ${__status}
}


########################################


# trap 'echo "Ciao!"' ERR

for test in ${tests[@]}
do
    if (( tests_enabled["${test}"] ))
    then
        bib.print "Testing “${test}”\n"

        run_test "${test}"
        case ${?} in
            ${BIB_E_NEXISTS} )
                bib.print "&RED*Test “${test}” not found in path*\n"
                status=${BIB_E_NOK}
            ;;

            ${BIB_E_TESTFAIL} )
                bib.print "&YLW*Test “${test}” failed*\n"
                status=${BIB_E_NOK}
            ;;

            ${BIB_E_OK} )
                bib.print "&GRN*Test “${test}” OK*\n"
            ;;
        esac

    else
        bib.print "*Test “${test}” skipped*\n"
    fi
done

exit ${status}
